config/routes.rb
Rails.application.routes.draw do
  resources :users do
    member do
      get :expand
      get :collapse
    end

    collection do
      delete :destroy_multiple
      patch :update_multiple
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "users#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
  enum :status, {
    unknown: 0,
    warn: 2,
    alert: 3,
    approved: 4,
  }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  PER_PAGE = 20
  before_action :build_filter_and_search, only: [:index]
  before_action :build_pagination_calculator, only: [:index]
  before_action :load_user, only: [:expand, :collapse, :show, :edit, :update, :destroy]
  before_action :load_bulk_action_users, only: [:destroy_multiple, :update_multiple]

  helper_method :filter_and_search_params

  def index
    @users = current_page_association
  end

  def create
  end

  def show
    respond_to do |format|
      format.turbo_stream
      format.html
    end
  end

  def expand
    respond_to do |format|
      format.turbo_stream
      format.html { redirect_to action: :show}
    end
  end

  def collapse
    respond_to do |format|
      format.turbo_stream
      format.html { redirect_to action: :index}
    end
  end

  def edit
  end

  def update
    @user.update!(update_params)

    respond_to do |format|
      format.turbo_stream
      format.html { redirect_to action: :show}
    end
  end

  def destroy
    @user.destroy
    respond_to do |format|
      format.turbo_stream
      format.html { redirect_to action: :index}
    end
  end

  def destroy_multiple
    @bulk_action_users.destroy_all
    respond_to do |format|
      format.turbo_stream
      format.html { redirect_to action: :index}
    end
  end

  def update_multiple
    @bulk_action_users.update_all(status: bulk_action_params[:status])
    respond_to do |format|
      format.turbo_stream
      format.html { redirect_to action: :index}
    end
  end

  protected

  def load_bulk_action_users
    @bulk_action_users = User.where(id: bulk_action_params[:user_ids])
  end

  def filter_and_search_params
    params.permit(filter_and_search: [:status, :note_presence, :note, :email, :name])
  end

  def build_filter_and_search
    @filter_and_search = FilterAndSearch.new(filter_and_search_params[:filter_and_search])
  end

  def update_params
    params.require(:user).permit(:status, :notes)
  end

  def bulk_action_params
    params.require(:bulk_action).permit(:status, user_ids: [])
  end

  def load_user
    @user = User.find(params[:id])
  end

  def base_association
    @filter_and_search.filter(scope: User.all)
  end

  def current_page_association
    offset = PaginationCalculator.pagination_offset(page: params[:page].to_i, per_page: PER_PAGE)
    base_association.limit(PER_PAGE).offset(offset)
  end

  def build_pagination_calculator
    @pagination_calculator = PaginationCalculator.new(
      current_page: params[:page].to_i,
      per_page: PER_PAGE,
      total_items: base_association.count,
      current_item_count: current_page_association.count
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def user_name(user)
    return [user.first_name, user.last_name].join(' ')
  end

  def domain_url(domain)
    URI::HTTP.build(host: domain).to_s
  end

  def user_status(user)
    status_badge(user.status)
  end

  def status_badge(status)
    case status.to_sym
    when :unknown
      return "❓"
    when :warn
      return "⚠️"
    when :alert
      return "🚨"
    when :approved
      return "✅"
    end
  end

  def bulk_actions_user_checkbox(user)
    check_box_tag(field_name(:bulk_action, :user_ids, multiple: true), user.id, false, form: 'bulk-actions')
  end

  def bulk_actions_status_field_name
    field_name(:bulk_action, :status)
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DummyJsonUsersCrud</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/_add_user_form.html.erb
<%= form_with model: user, data: { turbo_stream: true } do |f| %>
  <%= form_with model: user, data: { turbo_stream: true } do |f| %>
    <fieldset>
      <legend>User basics</legend>
      <table>
        <tr><th><%= f.label :dummy_json_id, "External ID" %></th><td><%= f.text_field :dummy_json_id, required: true, placeholder: "1234", inputmode: :numeric, pattern: "[0-9]*" %>
        <tr><th><%= f.label :first_name, "First name" %></th><td><%= f.text_field :first_name, required: true, placeholder: "Grace", autocomplete: "given-name" %>
        <tr><th><%= f.label :last_name, "Last name" %></th><td><%= f.text_field :last_name, required: true, placeholder: "Hopper", autocomplete: "family-name" %></td></tr>
        <tr><th><%= f.label :email, "Email" %></th><td><%= f.email_field :email, required: true, placeholder: "grace@example.com", autocomplete: "email" %></td></tr>
        <tr><th><%= f.label :domain, "Domain" %></th><td><%= f.text_field :domain, required: true, placeholder: "example.com", autocomplete: "email" %></td></tr>
        <tr><th><%= f.label :ip_address, "IP Address" %></th><td><%= f.text_field :ip_address, required: true, placeholder: "127.0.0.1" %></td></tr>
        <tr><th><%= f.label :mac_address, "MAC Address" %></th><td><%= f.text_field :ip_address, required: true, placeholder: "00:25:96:12:34:56" %></td></tr>

        <tr><th><%= f.label :user_agent, "User Agent" %></th><td><%= f.text_area :user_agent, placeholder: "Mozilla/5.0 (compatible; YandexAccessibilityBot/3.0; +http://yandex.com/bots)" %></td></tr>
        </td></tr>
      </table>
    </fieldset>
    <fieldset>
      <legend>Status</legend>
      <ul>
        <li>
          <%= f.radio_button :status, :unknown %>
          <%= f.label :status, value: :unknown do %>
            <%= status_badge(:unknown) %> Unknown
          <% end %>
        </li>
        <li>
          <%= f.radio_button :status, :warn %>
          <%= f.label :status, value: :warn do %>
            <%= status_badge(:warn) %> Warn
          <% end %>
        </li>
        <li>
          <%= f.radio_button :status, :alert %>
          <%= f.label :status, value: :alert do %>
            <%= status_badge(:alert) %> Alert
          <% end %>
        </li>
        <li>
          <%= f.radio_button :status, :approved %>
          <%= f.label :status, value: :approved do %>
            <%= status_badge(:approved) %> Approved
          <% end %>
        </li>
      </ul>
    </fieldset>

    <table>
      <thead><tr><th><%= f.label :notes %></th></tr></thead>
      <tbody><tr><td><%= f.text_area :notes, placeholder: "Any security notes here…" %></td></tr></tbody>
    </table>

    <section class="actions">
      <%= f.button "Record User", type: "submit" %>
    </section>
  <% end %>
<% end %>

app/views/users/_expanded_user_table_row.html.erb
<tbody id="<%= dom_id(user, :row) %>">
  <tr>
    <td><%= bulk_actions_user_checkbox(user) %></td>
    <td><%= user_status(user) %></td>
    <td><%= user_name(user) %></td>
    <td><%= mail_to(user.email) %></td>
    <td><%= link_to(user.domain, domain_url(user.domain)) %></td>
    <td><code><%= user.ip_address %></code></td>
    <td><code><%= user.mac_address %></code></td>
    <td>
      <%= link_to "Close", collapse_user_path(user), data: { turbo_stream: true } %>
    </td>
  </tr>
  <tr>
    <td colspan="6">
      <details open>
        <summary>User Agent</summary>
        <code><%= user.user_agent %></code>
      </details>

      <%= form_with model: user, data: { turbo_stream: true } do |f| %>
        <fieldset>
          <legend>Status</legend>
          <ul>
            <li>
              <%= f.radio_button :status, :unknown %>
              <%= f.label :status, value: :unknown do %>
                <%= status_badge(:unknown) %> Unknown
              <% end %>
            </li>
            <li>
              <%= f.radio_button :status, :warn %>
              <%= f.label :status, value: :warn do %>
                <%= status_badge(:warn) %> Warn
              <% end %>
            </li>
            <li>
              <%= f.radio_button :status, :alert %>
              <%= f.label :status, value: :alert do %>
                <%= status_badge(:alert) %> Alert
              <% end %>
            </li>
            <li>
              <%= f.radio_button :status, :approved %>
              <%= f.label :status, value: :approved do %>
                <%= status_badge(:approved) %> Approved
              <% end %>
            </li>
          </ul>
        </fieldset>
        <table>
          <thead><tr><th><%= f.label :notes %></th></tr></thead>
          <tbody><tr><td><%= f.text_area :notes, placeholder: "Any security notes here…" %></td></tr></tbody>
        </table>

        <section class="actions">
          <%= f.button "Cancel", type: :submit, formaction: collapse_user_path(user), formmethod: :get %>
          <%= f.button "Update", type: "submit" %>
        </section>
      <% end %>
    </td>
  </tr>
</tbody>

app/views/users/_filter_and_search_params_hidden_fields.html.erb
<%= hidden_field_tag field_name(:filter_and_search, :status), filter_and_search_params.dig(:filter_and_search, :status) %>
<%= hidden_field_tag field_name(:filter_and_search, :note_presence), filter_and_search_params.dig(:filter_and_search, :note_presence) %>
<%= hidden_field_tag field_name(:filter_and_search, :note), filter_and_search_params.dig(:filter_and_search, :note) %>
<%= hidden_field_tag field_name(:filter_and_search, :email), filter_and_search_params.dig(:filter_and_search, :email) %>
<%= hidden_field_tag field_name(:filter_and_search, :name), filter_and_search_params.dig(:filter_and_search, :name) %>

app/views/users/_user_table_row.html.erb
<tbody id="<%= dom_id(user, :row) %>">
  <tr>
    <td><%= bulk_actions_user_checkbox(user) %></td>
    <td><%= user_status(user) %></td>
    <td><%= user_name(user) %></td>
    <td><%= mail_to(user.email) %></td>
    <td><%= link_to(user.domain, domain_url(user.domain)) %></td>
    <td><pre><%= user.ip_address %></pre></td>
    <td><pre><%= user.mac_address %></pre></td>
    <td>
      <%= link_to "Details", expand_user_path(user), data: { turbo_stream: true } %>
      <%= button_to "Delete", user_path(user), method: :delete, data: { turbo_stream: true, turbo_confirm: "Are you sure you want to delete this user?" } %>
    </td>
  </tr>
</tbody>

app/views/users/collapse.turbo_stream.erb
<%= turbo_stream.replace(dom_id(@user, "row")) do %>
  <%= render partial: "user_table_row", format: :html, locals: {user: @user} %>
<% end %>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/expand.turbo_stream.erb
<%= turbo_stream.replace(dom_id(@user, "row")) do %>
  <%= render partial: "expanded_user_table_row", format: :html, locals: {user: @user} %>
<% end %>

app/views/users/index.html.erb
<h1>User Audit Log</h1>

<%= form_with model: @filter_and_search, url: users_url, method: :get do |f| %>
  <h2>Filter &amp; Search</h2>
  <fieldset>
    <legend>Status</legend>

    <ul>
      <li><%= f.radio_button :status, '' %><%= f.label :status, " 👥 All users", value: '' %></li>
      <li>
        <%= f.radio_button :status, :unknown %>
        <%= f.label :status, value: :unknown do %>
          <%= status_badge(:unknown) %> Unknown users
        <% end %>
      </li>
      <li>
        <%= f.radio_button :status, :warn %>
        <%= f.label :status, value: :warn do %>
          <%= status_badge(:warn) %> Users with warnings
        <% end %>
      </li>
      <li>
        <%= f.radio_button :status, :alert %>
        <%= f.label :status, value: :alert do %>
          <%= status_badge(:alert) %> Users with an alert
        <% end %>
      </li>
      <li>
        <%= f.radio_button :status, :approved %>
        <%= f.label :status, value: :approved do %>
          <%= status_badge(:approved) %> Approved users
        <% end %>
      </li>
    </ul>
  </fieldset>

  <fieldset>
    <legend>Notes</legend>
    <p><%= f.check_box :note_presence %> <%= f.label :note_presence, "Has a note" %></p>
    <p><%= f.text_area :note, placeholder: "Note contains…" %></p>
  </fieldset>

  <fieldset>
    <legend>User details</legend>
    <table>
      <tr><th><%= f.label :name, "Name" %></th><td><%= f.search_field :name, placeholder: "Grace Hopper" %></td></tr>
      <tr><th><%= f.label :email, "Email" %></th><td><%= f.search_field :email, placeholder: "grace@example.com" %></td></tr>
    </table>
  </fieldset>

  <button type="submit">Filter</button>
<% end %>

<%= form_with id: "bulk-actions" do |f| %>
  <ul>
    <li>
      <%= f.button name: bulk_actions_status_field_name, value: :unknown, type: "submit", formmethod: :patch, formaction: update_multiple_users_url, data: {turbo_confirm: "Are you sure you want to mark these users as unknown?"} do %>
        Mark selected as <%= status_badge(:unknown) %> Unknown
      <% end %>
    </li>
    <li>
      <%= f.button name: bulk_actions_status_field_name, value: :warn, type: "submit", formmethod: :patch, formaction: update_multiple_users_url, data: {turbo_confirm: "Are you sure you want to mark these users with a warning?"} do %>
        Mark selected with a <%= status_badge(:warn) %> warning
      <% end %>
    </li>
    <li>
      <%= f.button name: bulk_actions_status_field_name, value: :alert, type: "submit", formmethod: :patch, formaction: update_multiple_users_url, data: {turbo_confirm: "Are you sure you want to mark these users with an alert?"} do %>
        Mark selected with an <%= status_badge(:alert) %> Alert
      <% end %>
    </li>

    <li>
      <%= f.button name: bulk_actions_status_field_name, value: :approved, type: "submit", formmethod: :patch, formaction: update_multiple_users_url, data: {turbo_confirm: "Are you sure you want to mark these users as approved?"} do %>
        Mark selected as <%= status_badge(:approved) %> Approved
      <% end %>
    </li>

    <li>
      <%= f.button name: nil, type: "submit", formmethod: :delete, formaction: destroy_multiple_users_url, data: {turbo_confirm: "Are you sure you want to delete these users?"} do %>
        🚮 Delete selected
      <% end %>
    </li>
  </ul>
<% end %>

<%= turbo_frame_tag "users" do %>
  <table>
    <thead>
      <tr>
        <th></th>
        <th>Status</th>
        <th>Name</th>
        <th>Email</th>
        <th>Domain</th>
        <th>IP Address</th>
        <th>MAC Address</th>
        <th></th>
      </tr>
    </thead>

    <%= render partial: "user_table_row", collection: @users, as: :user, cache: true %>
  </table>
<% end %>

<%= form_with url: users_url, method: :get, id: "goto-page-form" do |f| %>
  <%= render partial: "filter_and_search_params_hidden_fields", locals: {f: f} %>
<% end %>

<%= form_with url: users_url, method: :get do |f| %>
  <%= render partial: "filter_and_search_params_hidden_fields", locals: {f: f} %>
  <% if @pagination_calculator.has_previous_page? %>
    <%= f.button type: "submit", name: "page", value: 1 do %>
      First
    <% end %>

    <%= f.button type: "submit", name: "page", value: @pagination_calculator.previous_page do %>
      Previous
    <% end %>
  <% end %>

  <label for="page-goto">Page</label>
  <%= text_field_tag :page, @pagination_calculator.current_page, id: "page-goto", form: "goto-page-form" %>
  of <%= @pagination_calculator.last_page_number %>
  <button type="submit" form='goto-page-form'>Go</button>

  <% if @pagination_calculator.has_next_page? %>
    <%= f.button type: "submit", name: "page", value: @pagination_calculator.next_page do %>
      Next
    <% end %>

    <%= f.button type: "submit", name: "page", value: @pagination_calculator.last_page_number do %>
      Last
    <% end %>
  <% end %>
<% end %>

<section>
  <h2>Record a user</h2>
  <%= render partial: "add_user_form", locals: {user: User.new} %>
</section>

app/views/users/show.html.erb
<h1>User Details</h1>


<table>
  <tr>
    <th>Status</th>
    <td><%= user_status(@user) %> <%= @user.status.humanize %></td>
  </tr>
  <tr>
    <th>Name</th>
    <td><%= user_name(@user) %></td>
  </tr>
  <tr>
    <th>Email</th>
    <td><%= mail_to(@user.email) %></td>
  </tr>
  <tr>
    <th>Domain</th>
    <td><%= link_to(@user.domain, domain_url(@user.domain)) %></td>
  </tr>
  <tr>
    <th>IP Address</th>
    <td><code><%= @user.ip_address %></code></td>
  </tr>
  <tr>
    <th>MAC Address</th>
    <td><code><%= @user.mac_address %></code></td>
  </tr>
  <tr>
    <th>User Agent</th>
    <td><code><%= @user.user_agent %></code></td>
  </tr>
</table>

app/views/users/update.turbo_stream.erb
<%= turbo_stream.replace(dom_id(@user, "row")) do %>
  <%= render partial: "user_table_row", format: :html, locals: {user: @user} %>
<% end %>